[package]
name = "w65xx-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.17"
strum = { version = "0.25.0", features = ["derive"] }
